# Generated by Django 3.2.9 on 2022-01-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['brand']},
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='mark',
            new_name='brand',
        ),
    ]
