# Generated by Django 3.2.9 on 2022-01-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
