# Generated by Django 3.2.9 on 2022-01-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
